const DB_KEY='pikro_db';
function getDB(){if(typeof window==='undefined')return {users:[],orders:[],reviews:[],currentUser:null};try{return JSON.parse(localStorage.getItem(DB_KEY)||'{"users":[],"orders":[],"reviews":[],"currentUser":null}')}catch{return {users:[],orders:[],reviews:[],currentUser:null}}}
function saveDB(db:any){localStorage.setItem(DB_KEY,JSON.stringify(db))}
export function gId(){return'id_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
export function register(phone:string,name:string,role:string){const db=getDB();if(db.users.find((u:any)=>u.phone===phone))return{ok:false,msg:'این شماره قبلاً ثبت شده'};const u={id:gId(),phone,name,role,rating:5,totalDeliveries:0,level:1,isOnline:false,createdAt:new Date().toISOString()};db.users.push(u);db.currentUser=u;saveDB(db);return{ok:true,user:u}}
export function login(phone:string){const db=getDB();const u=db.users.find((u:any)=>u.phone===phone);if(!u)return{ok:false,msg:'کاربری با این شماره یافت نشد'};db.currentUser=u;saveDB(db);return{ok:true,user:u}}
export function getCurrentUser(){try{return getDB().currentUser}catch{return null}}
export function logout(){const db=getDB();db.currentUser=null;saveDB(db)}
export function createOrder(d:any){const db=getDB();const o={id:gId(),orderNumber:db.orders.length+1000,customerId:d.customerId,customerName:d.customerName,courierId:null,courierName:null,courierPhone:null,status:'searching',packageType:d.packageType,description:d.description||'',isUrgent:d.isUrgent||false,costRial:d.costRial||45000,distanceKm:d.distanceKm||1.5,estimatedMin:d.estimatedMin||25,vehicleType:d.vehicleType||'walk',pickupAddr:d.pickupAddr,dropoffAddr:d.dropoffAddr,paymentMethod:d.paymentMethod||'cash',pickupOTP:String(Math.floor(10000+Math.random()*90000)),dropoffOTP:String(Math.floor(10000+Math.random()*90000)),createdAt:new Date().toISOString(),acceptedAt:null,deliveredAt:null,locations:[]};db.orders.push(o);saveDB(db);return{ok:true,order:o}}
export function getOrders(f?:{userId?:string;role?:string}){const db=getDB();let o=[...db.orders];if(f?.role==='customer')o=o.filter((x:any)=>x.customerId===f.userId);return o.sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())}
export function getOrder(id:string){return getDB().orders.find((o:any)=>o.id===id)||null}
export function acceptOrder(oId:string,cId:string,cName:string,cPhone:string){const db=getDB();const o=db.orders.find((x:any)=>x.id===oId);if(!o||o.status!=='searching')return{ok:false,msg:'سفارش دیگر در دسترس نیست'};o.courierId=cId;o.courierName=cName;o.courierPhone=cPhone;o.status='accepted';o.acceptedAt=new Date().toISOString();saveDB(db);return{ok:true,order:o}}
export function updateOrderStatus(oId:string,status:string){const db=getDB();const o=db.orders.find((x:any)=>x.id===oId);if(!o)return{ok:false};o.status=status;if(status==='delivered')o.deliveredAt=new Date().toISOString();saveDB(db);return{ok:true}}
export function toggleCourierOnline(cId:string){const db=getDB();const u=db.users.find((x:any)=>x.id===cId);if(u){u.isOnline=!u.isOnline;saveDB(db);return{ok:true,isOnline:u.isOnline}}return{ok:false}}
export function getAdminStats(){const db=getDB();return{activeOrders:db.orders.filter((o:any)=>!['delivered','cancelled'].includes(o.status)).length,totalDelivered:db.orders.filter((o:any)=>o.status==='delivered').length,couriersOnline:db.users.filter((u:any)=>u.role==='courier'&&u.isOnline).length,totalOrders:db.orders.length,totalUsers:db.users.length}}
export function getCourierStats(cId:string){const db=getDB();const d=db.orders.filter((o:any)=>o.courierId===cId&&o.status==='delivered');const today=new Date().toDateString();const ti=d.filter((o:any)=>new Date(o.createdAt).toDateString()===today).reduce((s:number,o:any)=>s+o.costRial,0);return{totalDeliveries:d.length,todayIncome:ti,totalIncome:d.reduce((s:number,o:any)=>s+o.costRial,0)}}